### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by 4n70w4** [dormouse-jenny/parser_nostroy#1]
How to run it?

**Comment by leprick0n** [comment]
Не смог запустить. Выпадает в ошибки (

Парсинг реестра СРО. Всего 16 страниц.
Парсинг 6% (1/16)
Traceback (most recent call last):

  File "C:\Users\user\press\test3.py", line 318, in <module>
    main()

  File "C:\Users\user\press\test3.py", line 275, in main
    parse_SRO_table(get_html(BASE_URL + "?sort=u.registrationnumber&direction=ASC&page=%d" %page))

  File "C:\Users\user\press\test3.py", line 255, in parse_SRO_table
    for row in table.find_all('tr', class_='sro-link'):

AttributeError: 'NoneType' object has no attribute 'find_all'
